import {
  DataTypes,
  Model,
  type CreationOptional,
  type InferAttributes,
  type InferCreationAttributes,
} from 'sequelize';

import { sequelize } from '../config/database.js';

/**
 * A file that arrived with a message.
 *
 * Separate from `CustomerAttachment` because the owner differs — those belong
 * to a customer record, these to one message in a conversation. The storage
 * RULES are shared rather than duplicated: same path, same ceiling, same
 * content-sniffed type check, same rule that nothing under the storage path is
 * ever served statically.
 *
 * `is_inline` carries FR-036. An HTML email references images by Content-ID: a
 * signature logo, a tracking pixel, an avatar from a quoted thread. None is a
 * document the customer chose to send, and listing them buries the one file
 * they did send under four they never knew about.
 */
export class MessageAttachment extends Model<
  InferAttributes<MessageAttachment>,
  InferCreationAttributes<MessageAttachment>
> {
  declare id: CreationOptional<number>;
  declare message_id: number;
  /** As the sender named it. Displayed; never used to build a path. */
  declare file_name: string;
  /** Sniffed from content. The sender's Content-Type is a claim, not a fact. */
  declare content_type: string;
  declare byte_size: number;
  /** Generated by the service, never derived from anything a sender supplied. */
  declare storage_key: string;
  declare is_inline: CreationOptional<boolean>;
  declare readonly created_at: CreationOptional<Date>;
  declare readonly updated_at: CreationOptional<Date>;
}

MessageAttachment.init(
  {
    id: { type: DataTypes.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true },
    message_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
    file_name: { type: DataTypes.STRING(255), allowNull: false },
    content_type: { type: DataTypes.STRING(100), allowNull: false },
    byte_size: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
    storage_key: { type: DataTypes.STRING(255), allowNull: false },
    is_inline: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    created_at: DataTypes.DATE,
    updated_at: DataTypes.DATE,
  },
  { sequelize, modelName: 'MessageAttachment', tableName: 'message_attachments' },
);

export default MessageAttachment;
